name: JumpAndRun
version: 2.1
author: Rebux
description: Jump and Run Plugin

main: net.rebux.jumpandrun.Plugin

# This is only here to make sure this plugin is loaded after Multiverse-Core
# It is not a direct dependency
softdepend: [Multiverse-Core]

commands:
  jumpandrun:
    aliases: [jnr]
    permission: jumpandrun.manage
  top:
    description: Lists the top 5 players of the current Jump and Run
  practice:
    aliases: [prac]
    description: Toggle practice mode