name: JumpAndRun
version: 2.1
author: Rebux
description: Jump and Run Plugin
main: net.rebux.jumpandrun.Plugin
softdepend:
  - Multiverse-Core

commands:
  jumpandrun:
    aliases: [jnr]
    permission: jumpandrun.manage
  top:
    description: Lists the top 5 players of the current Jump and Run