name: JumpAndRun
version: 2.2
author: Rebux
description: Jump and Run Plugin
main: net.rebux.jumpandrun.Plugin
# This is only here to make sure that dependencies are loaded before this plugin
depend:
  - Multiverse-Core

commands:
  jumpandrun:
    aliases: [jnr]
    permission: jumpandrun.manage
  top:
    description: Lists the top 5 players of the current Jump and Run
  practice:
    aliases: [prac]
    description: Toggle practice mode